### ISSUE TITLE
Missing BOM/CPL file?

### ISSUE THREAD

**Issue by robcazzaro** [profdc9/STM32surface#1]
First of all, thanks for sharing this. I have a few "old and good" Blue Pills. and do no want to get a non-STM version

Since you explicitly mention that you selected only JLCPCB parts, I was hoping to also find an already created BOM/CPL file to get an immediate quote on their website. I know I could build my own, but before starting I wondered if maybe you meant to also add the BOM/CPL file and simply forgot, or if you do not plan to provide one

**Comment by profdc9** [comment]
Ok, I added STM32surface-BOM.xlsx and STM32surface-top.xlsx to the project
and tested it on JLCPCB's web site.  It appears to look fine on the
rendering with correct placement of the components.  The price for 5 total
was $27.76 with the $2 for the PCBs.

Things that are not included are the 6 mm through-hole button for the reset
button and a USB-B connector.  The USB-B connector is the big type which I
prefer because it is very rugged and is very standardized and therefore is
easy to get.

Dan

**Comment by profdc9** [comment]
Oh yeah, I forgot to mention the files are on the github...

Dan

**Comment by robcazzaro** [comment]
Thanks!
